#!/bin/sh
# Filename:      run-journalctl
# Purpose:       wrapper for getty setup to run journalctl with according options
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2.
################################################################################

exec /bin/journalctl -b -f

## END OF FILE #################################################################
