#!/bin/sh
# Filename:      run-multitail
# Purpose:       wrapper for getty setup to run multitail with according options
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>,
#                (c) Michael Gebetsroither <gebi@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2.
################################################################################

exec /usr/bin/multitail -o 'check_mail:0' /var/log/syslog

## END OF FILE #################################################################
