#!/bin/zsh
# Filename:      grml-info
# Purpose:       start browser with documentation for Grml (based) system
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2.
################################################################################

# allow customisation
[ -n "$distri" ] || distri=grml

if [ -r "/usr/share/doc/${distri}-docs/index.html" ] ; then
  # support easy customisation, file doesn't exist
  # by default on mainline Grml
  local PAGE="/usr/share/doc/${distri}-docs/index.html"
else
  local PAGE='/usr/share/doc/grml-docs/startpage.html'
fi

. /etc/grml/script-functions

# do we have X?
if [ -n "$DISPLAY" ] && check4progs x-www-browser &>/dev/null ; then
  exec x-www-browser "$PAGE"
elif check4progs links &>/dev/null ; then
  # no X: (or no x-www-browser)
  exec links "$PAGE"
elif check4progs www-browser &>/dev/null ; then
  exec www-browser "$PAGE"
fi

echo "Sorry, no browser available. Exiting.">&2
exit 1

## END OF FILE #################################################################
