#!/bin/sh
# Filename:      grml-iptstate
# Purpose:       wrapper around iptstate (top-like display of IP Tables state table entries)
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2.
################################################################################

# shellcheck disable=SC1091
. /etc/grml/script-functions
# shellcheck disable=SC1091
. /etc/grml/lsb-functions
check4progs iptstate || exit 1

if grep -q '_conntrack' /proc/modules ; then
   iptstate
else
   einfo "iptstate is a top-like display of IP Tables state table entries."
   echo
   ewarn "Module ip_conntrack is not present. Can not start iptstate therefore."
   eindent
     einfon "Do you want to load it and invoke iptstate afterwards? [YES|no] "
     read -r a
     a=$(echo "$a" | tr '[:upper:]' '[:lower:]')
     if [ "$a" = "yes" ] || [ "$a" = "y" ] || [ "$a" = "" ] ; then
        modprobe ip_conntrack ; RC=$?
	eend $RC
	[ "$RC" = 0 ] && exec iptstate
     else
        echo "Aborting as requested."
        exit 1
     fi
fi

## END OF FILE #################################################################
