#!/bin/sh
# Filename:      grml-setkeyboard
# Purpose:       set keyboard layout system-wide on grml system
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2.
################################################################################

PN="$(basename "$0")"

echo "${PN}: this program is deprecated." >&2
echo "${PN}: please use grml-lang instead." >&2
exit 1

## END OF FILE #################################################################
